---
openapi: 3.0.0
info:
  title: 'Ethereum Voting'
  license:
    name: gpl
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8080/v1'
paths:
  /elections:
    get:
      tags:
        - elections
      summary: 'Listar elecciones'
      operationId: list_elections
      responses:
        '200':
          description: 'Lista de elecciones con sendas informaciones'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Elections'
        '401':
          description: 'No Autorizado'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: 'Error Inesperado'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-openapi-router-controller: democracy_server.controllers.elections_controller
    post:
      tags:
        - elections
      summary: 'Crear una elección'
      operationId: create_election
      requestBody:
        description: 'Parámetros para crear la elección'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateElection'
        required: true
      responses:
        '201':
          description: 'Identificador de la elección creada'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatedElection'
        '401':
          description: 'No Autorizado'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: 'Error Inesperado'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-openapi-router-controller: democracy_server.controllers.elections_controller
  '/elections/{electionId}':
    get:
      tags:
        - elections
      summary: 'Obtener información de una elección a partir de su identificador'
      operationId: show_election_by_id
      parameters:
        -
          name: electionId
          in: path
          description: 'El identificador de la elección'
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        '200':
          description: 'Información de la elección'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Election'
        '401':
          description: 'No se tiene acceso a la elección especificada'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: 'No se ha encontrado la elección'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: 'Error Inesperado'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-openapi-router-controller: democracy_server.controllers.elections_controller
  '/elections/{electionId}/candidates':
    get:
      tags:
        - candidates
      summary: 'Lisar los candiatos de una elección'
      operationId: list_election_candidates
      parameters:
        -
          name: electionId
          in: path
          description: 'Identificador de la elección'
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        '200':
          description: 'Lista de los candidatos'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Candidate'
        '401':
          description: 'No Autorizado'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: 'No se ha encontrado la elección'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: 'Error Inesperado'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-openapi-router-controller: democracy_server.controllers.candidates_controller
  '/elections/{electionId}/candidates/{candidateId}':
    get:
      tags:
        - candidates
      summary: 'Obtener la información de un candidato'
      operationId: lookup_candidate
      parameters:
        -
          name: electionId
          in: path
          description: 'Identificador de la elección'
          required: true
          style: simple
          explode: false
          schema:
            type: string
        -
          name: candidateId
          in: path
          description: 'Identificador del candidato'
          required: true
          style: simple
          explode: false
          schema:
            type: integer
      responses:
        '200':
          description: 'Información del candidato'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Candidate'
        '401':
          description: 'Not Authorized'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: 'No se ha encontrado la elección o el candidato'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: 'Error Inesperado'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-openapi-router-controller: democracy_server.controllers.candidates_controller
  '/elections/{electionId}/candidates/{candidateId}/votes':
    get:
      tags:
        - votes
      summary: 'Get votes for a candidate'
      operationId: get_candidate_votes
      parameters:
        -
          name: electionId
          in: path
          description: 'Identificador de la elección'
          required: true
          style: simple
          explode: false
          schema:
            type: string
        -
          name: candidateId
          in: path
          description: 'Identificador del candidato'
          required: true
          style: simple
          explode: false
          schema:
            type: integer
      responses:
        '200':
          description: 'Número de votos del candidato'
          content:
            application/json:
              schema:
                required:
                  - votes
                properties:
                  votes:
                    type: integer
                    format: int64
                example:
                  votes: 0
                x-content-type: application/json
        '401':
          description: 'No Autorizado'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: 'Candidato o Elección no encontrado'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: 'Error Inesperado'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-openapi-router-controller: democracy_server.controllers.votes_controller
    post:
      tags:
        - votes
      summary: 'Votar por un candidato'
      operationId: create_candidate_vote
      parameters:
        -
          name: electionId
          in: path
          description: 'Identificador de la Elección'
          required: true
          style: simple
          explode: false
          schema:
            type: string
        -
          name: candidateId
          in: path
          description: 'Identificador del candidato'
          required: true
          style: simple
          explode: false
          schema:
            type: integer
      requestBody:
        description: 'Parámetros necesario para votar a un candidato'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateVote'
        required: true
      responses:
        '204':
          description: 'El voto ha sido cargado en el sistema'
        '401':
          description: 'El usuario no está autorizado o ya ha votado'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: 'Elección o candidato no encontrado'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: 'Error inesperado'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-openapi-router-controller: democracy_server.controllers.votes_controller
components:
  schemas:
    Candidate:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        votes:
          type: integer
          format: int64
      example:
        name: 'Partido Único'
        votes: 4
        id: 0
    CreateCandidate:
      required:
        - name
      properties:
        name:
          type: string
    Election:
      required:
        - id
        - name
      properties:
        id:
          type: string
        name:
          type: string
        candidates:
          type: array
          items:
            $ref: '#/components/schemas/Candidate'
      example:
        candidates:
          -
            name: 'Partido Fuerte'
            votes: 0
            id: 0
          -
            name: 'Partido Inteligente'
            votes: 0
            id: 0
        name: name
        id: id
    CreatedElection:
      required:
        - id
      properties:
        id:
          type: string
    CreateElection:
      required:
        - account
        - name
        - pkey
      properties:
        name:
          type: string
        candidates:
          type: array
          items:
            $ref: '#/components/schemas/CreateCandidate'
        account:
          type: string
        pkey:
          type: string
    Elections:
      type: array
      items:
        $ref: '#/components/schemas/Election'
    CreateVote:
      required:
        - account
        - pkey
      properties:
        account:
          type: string
        pkey:
          type: string
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
