# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from democracy_server.models.base_model_ import Model
from democracy_server import util


class CreatedElection(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None):  # noqa: E501
        """CreatedElection - a model defined in Swagger

        :param id: The id of this CreatedElection.  # noqa: E501
        :type id: str
        """
        self.swagger_types = {
            'id': str
        }

        self.attribute_map = {
            'id': 'id'
        }
        self._id = id

    @classmethod
    def from_dict(cls, dikt) -> 'CreatedElection':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreatedElection of this CreatedElection.  # noqa: E501
        :rtype: CreatedElection
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this CreatedElection.


        :return: The id of this CreatedElection.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this CreatedElection.


        :param id: The id of this CreatedElection.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id
