# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from democracy_server.models.base_model_ import Model
from democracy_server import util

class CreateVote(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, account: str=None, pkey: str=None):  # noqa: E501
        """CreateVote - a model defined in Swagger

        :param account: The account of this CreateVote.  # noqa: E501
        :type account: str
        :param pkey: The pkey of this CreateVote.  # noqa: E501
        :type pkey: str
        """
        self.swagger_types = {
            'account': str,
            'pkey': str
        }

        self.attribute_map = {
            'account': 'account',
            'pkey': 'pkey'
        }
        self._account = account
        self._pkey = pkey

    @classmethod
    def from_dict(cls, dikt) -> 'CreateVote':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateVote of this CreateVote.  # noqa: E501
        :rtype: CreateVote
        """
        return util.deserialize_model(dikt, cls)

    @property
    def account(self) -> str:
        """Gets the account of this CreateVote.


        :return: The account of this CreateVote.
        :rtype: str
        """
        return self._account

    @account.setter
    def account(self, account: str):
        """Sets the account of this CreateVote.


        :param account: The account of this CreateVote.
        :type account: str
        """
        if account is None:
            raise ValueError("Invalid value for `account`, must not be `None`")  # noqa: E501

        self._account = account

    @property
    def pkey(self) -> str:
        """Gets the pkey of this CreateVote.


        :return: The pkey of this CreateVote.
        :rtype: str
        """
        return self._pkey

    @pkey.setter
    def pkey(self, pkey: str):
        """Sets the pkey of this CreateVote.


        :param pkey: The pkey of this CreateVote.
        :type pkey: str
        """
        if pkey is None:
            raise ValueError("Invalid value for `pkey`, must not be `None`")  # noqa: E501

        self._pkey = pkey
