# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from democracy_server.models.base_model_ import Model
from democracy_server.models.election import Election  # noqa: F401,E501
from democracy_server import util


class Elections(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self):  # noqa: E501
        """Elections - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'Elections':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Elections of this Elections.  # noqa: E501
        :rtype: Elections
        """
        return util.deserialize_model(dikt, cls)
