# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from democracy_server.models.base_model_ import Model
from democracy_server.models.candidate import Candidate  # noqa: F401,E501
from democracy_server import util


class Election(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, name: str=None, description: str=None, candidates: List[Candidate]=None):  # noqa: E501
        """Election - a model defined in Swagger

        :param id: The id of this Election.  # noqa: E501
        :type id: str
        :param name: The name of this Election.  # noqa: E501
        :type name: str
        :param description: The description of this Election.  # noqa: E501
        :type description: str
        :param candidates: The candidates of this Election.  # noqa: E501
        :type candidates: List[Candidate]
        """
        self.swagger_types = {
            'id': str,
            'name': str,
            'description': str,
            'candidates': List[Candidate]
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'description': 'description',
            'candidates': 'candidates'
        }
        self._id = id
        self._name = name
        self._description = description
        self._candidates = candidates

    @classmethod
    def from_dict(cls, dikt) -> 'Election':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Election of this Election.  # noqa: E501
        :rtype: Election
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Election.


        :return: The id of this Election.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Election.


        :param id: The id of this Election.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this Election.


        :return: The name of this Election.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Election.


        :param name: The name of this Election.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this Election.


        :return: The description of this Election.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this Election.


        :param description: The description of this Election.
        :type description: str
        """

        self._description = description

    @property
    def candidates(self) -> List[Candidate]:
        """Gets the candidates of this Election.


        :return: The candidates of this Election.
        :rtype: List[Candidate]
        """
        return self._candidates

    @candidates.setter
    def candidates(self, candidates: List[Candidate]):
        """Sets the candidates of this Election.


        :param candidates: The candidates of this Election.
        :type candidates: List[Candidate]
        """

        self._candidates = candidates
